<%
sub entete

 response.write"<table width='770' border='0' align='center' cellpadding='0' cellspacing='0'>"
 response.write"<tr><td align='center'>"
 response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=770 HEIGHT=750>"
 response.write"<TR><TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=77>"
 response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=770 HEIGHT=77>"
 'response.write"<TR><TD WIDTH=15 HEIGHT=77 COLSPAN=1 ROWSPAN=1 SIZE=3><font color='#FFCC33' size='4' face='Verdana, Arial, Helvetica, sans-serif'><B>&nbsp;</TD>"
 response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=212 HEIGHT=77 VAlign='Bottom'> <object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0' width='212' height='67'>"
 response.write"<param name='movie' value='gpsnew2.swf'><param name='quality' value='high'><embed src='gpsnew2.swf' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' type='application/x-shockwave-flash' width='212' height='77'></embed><noembed>"
 'response.write"<div id='oilogistic' style='position:absolute; width:700px; height:300px; z-index:1; left: 28px; top: 26px; visibility: hidden'>"

 response.write"<a href='petroleum_logistic/oilogistic.html'>oilogistic</a>"
 response.write"<a href='petroleum_logistic/oillogistic.html'>oillogistic</a>"
 response.write"<a href='petroleum_logistic/oil_logistic.html'>oil logistic</a>"
 response.write"<a href='petroleum_logistic/petroleum_supply_center_libya.html'>petroleum supply center libya</a>"
 response.write"<a href='petroleum_logistic/petroleum_equipment_zarzis.html'>petroleum equipment zarzis</a>"
 response.write"<a href='petroleum_logistic/petroleum_logistic_zarzis.html'>petroleum logistic zarzis</a>"
 response.write"<a href='petroleum_logistic/petroleum_logistic_libya.html'>petroleum logistic libya</a>"
 response.write"<a href='petroleum_logistic/petroleum_logistic_solution.html'>petroleum logistic solution</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_provider.html'>oil logistic provider</a>"
 response.write"<a href='petroleum_logistic/petroleum_logistic_provider_libya.html'>petroleum logistic provider libya</a>"
 response.write"<a href='petroleum_logistic/industry_oil_outsourcing.html'>industry oil outsourcing</a>"
 response.write"<a href='petroleum_logistic/petroleum_equipment_warehousing_libya.html'>petroleum equipment warehousing libya </a><h1> petroleum logistic from zarzis to libya and hassi mesaoud: oil logistic, oil transportation, oil equipment, road survey and warehousing facilities</h1>"
 response.write"</div><p>"
 response.write"<a href='petroleum_logistic/heavy_loads_transportation.html'>heavy loads transportation</a>"
 response.write"<a href='petroleum_logistic/petroleum_logistic_project.html'>petroleum logistic project</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_project.html'>oil logistic project</a>"
 response.write"<a href='petroleum_logistic/oil_equipment_transportation.html'>oil equipment transportation</a>"
 response.write"<a href='petroleum_logistic/transport_delicate_oil_materiel.html'>transport delicate oil materiel</a>"
 response.write"<a href='petroleum_logistic/road_survey_oil_transportation.html'>road survey oil transportation</a>"
 response.write"<a href='petroleum_logistic/oil_transportation_supervision.html'>oil transportation supervision</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_liby.html'>oil logistic libya</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_tunisia.html'>oil logistic tunisia</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_zarzis.html'>oil logistic zarzis</a>"
 response.write"<a href='petroleum_logistic/oil_logistic_hassi_messaoud.html'>oil logistic hassi messaoud</a>"
 response.write"<a href='petroleum_logistic/petroleum_manpower.html'>petroleum manpower</a>"
 response.write"<a href='petroleum_logistic/oil_equipment_hassi_messaoud.html'>oil equipment hassi messaoud</a>"
 response.write"</p><p> petroleum supply center in zarzis near to libya and hassi messaoud-algeria. This oil logistic provider helps the oil and gas business from zarzis </p>"
 response.write"<p>oilogistic, oillogistics, oil logistic, petroleum supply center libya, petroleum equipment zarzis, petroleum logistic zarzis, petroleum logistic libya, petroleum logistic solution, oil logistic provider, petroleum logistic provider libya, industry oil outsourcing, petroleum equipment warehousing libya, heavy loads transportation, petroleum logistic project, oil logistic project, oil equipment transportation, transport delicate oil materiel, road survey oil transportation</p></noembed>"
 response.write"</object></TD>"
                response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=489 HEIGHT=77>" 
                  response.write"<! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=top_menu>"
                  response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=489 HEIGHT=77>"
                    response.write"<TR>" 
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=21 HEIGHT=25>" 
                      response.write"<IMG NAME='TOP_MENU0' SRC='images/bla_empt1.jpg' BORDER=0 width='21' height='25' ></TD>"
               '       response.write"<form name='form1' method='get' action='http://www.gps-oillogistics.com/index.cfm/type/search/'><TD HEIGHT=25 COLSPAN=5 ROWSPAN=1 align='right'><input name='keywords' type='text' id='keywords'>"
               '         response.write"<input type='submit' name='Submit' value='Search'>"
                       
			response.write"</TD>"
                      response.write"</form>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=7 HEIGHT=25>" 
                      response.write"<IMG NAME='TOP_MENU6' SRC='images/bla_empt7.jpg' BORDER=0 width='7' height='25' ></TD>"
                    response.write"</TR>"
                    response.write"<TR>" 
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=21 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU7' SRC='images/top_menu-2x1.jpg' BORDER=0 width='21' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=89 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU8' SRC='images/top_menu-2x2.jpg' BORDER=0 width='89' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=91 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU9' SRC='images/top_menu-2x3.jpg' BORDER=0 width='91' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=97 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU10' SRC='images/top_menu-2x4.jpg' BORDER=0 width='97' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=94 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU11' SRC='images/top_menu-2x5.jpg' BORDER=0 width='94' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=90 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU12' SRC='images/top_menu-2x6.jpg' BORDER=0 width='90' height='6' ></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=7 HEIGHT=6>" 
                      response.write"<IMG NAME='TOP_MENU13' SRC='images/top_menu-2x7.jpg' BORDER=0 width='7' height='6' ></TD>"
                    response.write"</TR>"
                    response.write"<TR>" 
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=21 HEIGHT=46>" 
                      response.write"<IMG NAME='TOP_MENU14' SRC='images/emp_top_menu.jpg' BORDER=0 width='21' height='46' ></TD>"
                      response.write"<TD WIDTH=89 HEIGHT=46 background='images/top_bt1.jpg'>" 
                        response.write"&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                        response.write"<a style='text-decoration: none' href='index.asp'>Home</a></span></TD>"
                      response.write"<TD WIDTH=91 HEIGHT=46 background='images/top_bt2.jpg'>" 
                        response.write"&nbsp;&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                        response.write"<a style='text-decoration: none' href='Services.asp'>Services</a></span></TD>"
                      response.write"<TD WIDTH=97 HEIGHT=46 background='images/top_bt3.jpg'>" 
                        response.write"&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                        response.write"<a style='text-decoration: none' href='References.asp'>References</a></span></TD>"
                      response.write"<TD WIDTH=94 HEIGHT=46 background='images/top_bt4.jpg'>" 
                        response.write"&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                        response.write"<a style='text-decoration: none' href='contact.asp'>Contact</a></span></TD>"
                      response.write"<TD WIDTH=90 HEIGHT=46 background='images/top_bt5.jpg'>" 
                        response.write"&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                        response.write"<a style='text-decoration: none' href='http://www.skolms.com/v2/login.aspx'>Intranet</a></span></TD>"
                      response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=7 HEIGHT=46>" 
                      response.write"<IMG NAME='TOP_MENU20' SRC='images/right_top_bt6.jpg' BORDER=0 width='7' height='46' ></TD>"

                    response.write"</TR>"
                  response.write"</TABLE>"
                  response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=top_menu>"
                response.write"</TD>"
                response.write"<TD HEIGHT=77 COLSPAN=1 ROWSPAN=1 background='images/max_right_logo.jpg'>&nbsp;</TD>"
              response.write"</TR>"
            response.write"</TABLE>"
            response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-1x1>"
          response.write"</TD>"
        response.write"</TR>"
        response.write"<TR>"
         response.write" <TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=482>"
            response.write"<! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1>"
            response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=770 HEIGHT=482>"
             response.write" <TR>"
                response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=223 HEIGHT=26>"
               response.write" <IMG NAME='OLOG_2X10' SRC='images/olog-2x1-1x1.jpg' BORDER=0 width='223' height='26' ></TD>"
               response.write" <TD HEIGHT=26 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>&nbsp;"
              response.write"  </TD>"
              response.write"</TR>"
              response.write"<TR>"
               response.write" <TD WIDTH=223 HEIGHT=456 bgcolor='#FFFFFF' valign='top'>"
                response.write"  <! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1>"
                  response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=223 HEIGHT=456>"
                   response.write" <TR>"
                     response.write" <TD WIDTH=223 HEIGHT=37 bgcolor='#FFFFFF' valign='top'>" 
                      response.write"  <IMG NAME='OLOG_2X1_2X10' SRC='images/olog-2x1-2x1-1x1.jpg' BORDER=0 width='223' height='37' ></TD>"
                   response.write" </TR>"
                   response.write" <TR>"
                     response.write" <TD WIDTH=223 HEIGHT=163 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>"
                       response.write" <! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1-2x1>"
                        response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=223 HEIGHT=163>"
                         response.write" <TR>"
                           response.write" <TD ROWSPAN=5 WIDTH=67 HEIGHT=163>&nbsp; </TD>"
                            response.write"<TD WIDTH=122 HEIGHT=30 background='images/but1.jpg'>&nbsp;&nbsp;&nbsp;&nbsp;"
                             response.write" <span class='forButton'>"
                            response.write"<a style='text-decoration: none' href='news.asp'>News</a></span></TD>"
                           response.write" <TD ROWSPAN=5 WIDTH=34 HEIGHT=163>&nbsp; </TD>"
                          response.write"</TR>"
                         response.write" <TR> "
                            response.write"<TD WIDTH=122 HEIGHT=30 COLSPAN=1 ROWSPAN=1 background='images/but1.jpg'>&nbsp;&nbsp;&nbsp;&nbsp;"
                              response.write"<span class='forButton'>"
                            response.write"<a style='text-decoration: none' href='Company.asp'>Company</a></span></TD>"
                         response.write" </TR>"
                         response.write" <TR>"
                           response.write" <TD WIDTH=122 HEIGHT=30 background='images/but1.jpg'>"
                             response.write" &nbsp;&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                            response.write"  <a style='text-decoration: none' href='Partners.asp'>Partners</a></span></TD>"
                         response.write" </TR>"
                          response.write"<TR>" 
                            response.write"<TD WIDTH=122 HEIGHT=30 background='images/but1.jpg'>"
                           response.write"  &nbsp;&nbsp;&nbsp;&nbsp; <span class='forButton'>"
                             response.write" <a style='text-decoration: none' href='FAQs.asp'>FAQ's</a></span></TD>"
                         response.write" </TR>"
                          response.write"<TR>"
                            response.write"<TD WIDTH=122 HEIGHT=30 background='images/but1.jpg'>"
                            response.write"  &nbsp;&nbsp;&nbsp;&nbsp; <span class='forButton'>"
			     response.write" <a style='text-decoration: none' href='Why-Zarzis.asp'>Why Zarzis</a></span><br><br>"

response.write" <!-- BEGIN ProvideSupport.com CODE -->"
response.write" <script language='JavaScript' src='http://image.providesupport.com/js/omda.js'></script><a href='http://www.providesupport.com' target='_blank'><img src='http://image.providesupport.com/image/omda.gif' border='0'></a><noscript><img src='http://image.providesupport.com/spacer.gif' width='142' height='59'></noscript>"
response.write" <!-- END ProvideSupport.com CODE -->"
			 
			response.write"</TD>"
                         response.write" </TR>"
                       response.write" </TABLE>"
                        response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1-2x1>"


                     response.write" </TD>"
                    response.write"</TR>"
                    response.write"<TR> "
                      response.write"<TD WIDTH=223 HEIGHT=59 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>"
                       response.write" <! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1-3x1>"
                       response.write" <br>"
                       response.write" <TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=223 HEIGHT=59>"
                       response.write"<TR>"
                         response.write"   <TD WIDTH=81 HEIGHT=59 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>&nbsp;"
                            response.write"</TD>"
                            response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=83 HEIGHT=59></TD>"
                            response.write"<TD WIDTH=59 HEIGHT=59 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>&nbsp;"
                            response.write"</TD>"
                          response.write"</TR>"
                        response.write"</TABLE>"
                       response.write" <! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1-3x1>"
                      response.write"</TD>"
                    response.write"</TR>"
                    response.write"<TR>"
                      response.write"<TD WIDTH=223 HEIGHT=197 COLSPAN=1 ROWSPAN=1 bgcolor='#FFFFFF'>"
                        response.write"<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0' width='223' height='197'>"
                          response.write"<param name='movie' value='whyzarzis.swf'>"
                         response.write" <param name='quality' value='High'>"
                         response.write" <param name='_cx' value='5900'>"
                         response.write" <param name='_cy' value='5212'>"
                         response.write" <param name='FlashVars' value>"
                          response.write"<param name='Src' value='whyzarzis.swf'>"
                         response.write" <param name='WMode' value='Window'>"
                         response.write" <param name='Play' value='-1'>"
                         response.write" <param name='Loop' value='-1'>"
                         response.write" <param name='SAlign' value>"
                         response.write" <param name='Menu' value='-1'>"
                         response.write" <param name='Base' value>"
                         response.write" <param name='AllowScriptAccess' value='always'>"
                         response.write" <param name='Scale' value='ShowAll'>"
                          response.write"<param name='DeviceFont' value='0'>"
                          response.write"<param name='EmbedMovie' value='0'>"
                          response.write"<param name='BGColor' value>"
                          response.write"<param name='SWRemote' value>"
                          response.write"<param name='MovieData' value>"
                          response.write"<embed src='whyzarzis.swf' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' type='application/x-shockwave-flash' width='223' height='197'></embed></object>" 
                      response.write"</TD>"
                    response.write"</TR>"
                 response.write" </TABLE>"
                 response.write" <! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x1>"
                response.write"</TD>"
                response.write"<TD HEIGHT=456 COLSPAN=1 ROWSPAN=1 valign='top' bgcolor='#FFFFFF'>"
                  response.write"<! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x2>"
				  
end sub
%>
<%

sub pieddepage
response.write"</TABLE>"
                  response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x2></TD>"
              response.write"</TR>"
           response.write" </TABLE>"
           response.write" <! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1>"
          response.write"</TD>"
       response.write" </TR>"
        response.write"<TR> "
         response.write" <TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=191> "
            response.write"<! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-3x1>"
            response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=770 HEIGHT=191>"
              response.write"<TR> "
                response.write"<TD WIDTH=770 HEIGHT=35 COLSPAN=1 ROWSPAN=1 align='center' background='images/botom_menu.jpg'>"
		response.write"<table width='300' border='0' cellpadding='0' cellspacing='0' class='forButton'>"
                 response.write" <tr>"
                   'response.write" <td width='80' align='center'><a href='Disclaimer.htm' class='forButton'>Disclaimer</a></td>"
                   'response.write" <td width='70' align='center'><a href='Copyright.htm' class='forButton'>Copyright</a></td>"
                   'response.write" <td width='80' align='center'><a href='Site-Map.htm' class='forButton'>Site Map</a></td>"
                   'response.write" <td align='center'><a href='contact.asp' class='forButton'>Contact us</a></td>"
                  response.write"</tr>"
                response.write"</table></TD>"
              response.write"</TR>"
              response.write"<TR> "
                response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=12>" 
               response.write" <IMG NAME='OLOG_3X11' SRC='images/btm_menu_line_gr.jpg' BORDER=0 width='770' height='12' ></TD>"
              response.write"</TR>"
              response.write"<TR> "
                response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=21>" 
                response.write"<IMG NAME='OLOG_3X12' SRC='images/btm_menu_line_ora.jpg' BORDER=0 width='770' height='21' ></TD>"
             response.write" </TR>"
              response.write"<TR>" 
               response.write" <TD ROWSPAN=1 COLSPAN=1 WIDTH=770 HEIGHT=6>"
              response.write"  <IMG NAME='OLOG_3X13' SRC='images/btm_men_lin_yell.jpg' BORDER=0 width='770' height='6' ></TD>"
              response.write"</TR>"
              response.write"<TR>" 
               response.write" <TD WIDTH=770 HEIGHT=78 bgcolor='#FF8500'><div align='center' class='forTextssmservices'>GPS - Parc d'activites economiques de Zarzis - BP 91 - Port de Zarzis 4337 - Tunisia<br>Tel Duty Manager 24/7 : +44 20 7558 8468 - Tel Tunisia +216 75 680 521 - Tel Tripoli +218 21 360 9870   <br>Fax UK : +44 20 7043 4828 - Fax Tunisia : +216 75 680 522 - Fax Tripoli : +218 21 360 9870 </div> </TD>"
              response.write"</TR>"
              response.write"<TR> "
                response.write"<TD WIDTH=770 HEIGHT=39 bgcolor='#FF8500'> <div align='center' class='forCopyright'>Copyright 2007 gps-oillogistics.com. All rights reserved. <br>Developed by <a href='http://www.accesstoebusiness.com/'>Access to eBusiness</a></div></TD>"
             response.write" </TR>"
           response.write" </TABLE>"
           response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-3x1>"
          response.write"</TD>"
        response.write"</TR>"
      response.write"</TABLE>"
      response.write"<! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog>"
    response.write"</td>"
  response.write"</tr>"
response.write"</table>"
end sub

'*****************

sub textpreparation
response.write"<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=547>"
  response.write"<TR>"
    response.write"<TD ROWSPAN=1 COLSPAN=1 WIDTH=88 HEIGHT=9> <IMG NAME='OLOG_2X1_2X20' SRC='images/olog-2x1-2x2-1x1.jpg' BORDER=0 width='88' height='9' ></TD>"
    response.write"<TD HEIGHT=9 COLSPAN=1 ROWSPAN=1 background='images/olog-2x1-2x2-1x2.jpg'></TD>"
  response.write"</TR>"
  response.write"<TR>"
    response.write"<TD WIDTH=88 HEIGHT=276 COLSPAN=1 ROWSPAN=1 background='images/mid_bdy_cornr.jpg'>"
      response.write"<! TableStart -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x2-2x1>"
     response.write" <! TableEnd -- Ulead SmartSaver Pro 3.0 -- Key=olog-2x1-2x2-2x1>"
      response.write"<table width='100%' height='100%' border='0' cellpadding='0' cellspacing='0'>"
       response.write" <tr>"
         response.write" <td valign='top' background='images/mid_bdy_cornr.jpg'> <img name='OLOG_2X1_2X2_2X10' src='images/up_bdy_corner.jpg' border=0 width='88' height='75' ></td>"
        response.write"</tr>"
        response.write"<tr>"
        response.write"  <td><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=88 HEIGHT=276>"
            response.write"  <TR>"
            response.write"<TD WIDTH=88 HEIGHT=75 COLSPAN=1 ROWSPAN=1 background='images/mid_bdy_cornr.jpg'>&nbsp; </TD>"
             response.write" </TR>"
             response.write" <TR>"
              response.write"  <TD ROWSPAN=1 COLSPAN=1 WIDTH=88 HEIGHT=127>&nbsp; </TD>"
              response.write"</TR>"
              response.write"<TR>"
               response.write" <TD WIDTH=88 HEIGHT=74 COLSPAN=1 ROWSPAN=1 background='images/mid_bdy_cornr.jpg'>&nbsp; </TD>"
             response.write"</TR>"
          response.write"</TABLE></td>"
        response.write"</tr>"
        response.write"<tr>"
         response.write" <td valign='bottom' background='images/mid_bdy_cornr.jpg'> <img name='OLOG_2X1_2X2_2X12' src='images/down_bdy_cornr.jpg' border=0 width='88' height='74' ></td>"
        response.write"</tr>"
   response.write" </table></TD>"
    response.write"<TD HEIGHT=276 valign='top' bgcolor='#7F84AA'>"
      response.write"<p class='Titles'>"

end sub
%>
